version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: rhythmiq_db
    environment:
      POSTGRES_DB: rhythmiq
      POSTGRES_USER: rhythmiq_user
      POSTGRES_PASSWORD: rhythmiq_dev_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rhythmiq_network

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: rhythmiq_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rhythmiq_network

  # FastAPI Backend
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rhythmiq_api
    environment:
      - DATABASE_URL=postgresql://rhythmiq_user:rhythmiq_dev_password@db:5432/rhythmiq
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-dev_secret_key_change_in_production}
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      - db
      - redis
    networks:
      - rhythmiq_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rhythmiq_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - rhythmiq_network
    command: npm start

  # n8n Automation Engine
  n8n:
    image: n8nio/n8n:latest
    container_name: rhythmiq_n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - rhythmiq_network

volumes:
  postgres_data:
  redis_data:
  n8n_data:

networks:
  rhythmiq_network:
    driver: bridge